name: HideAndSeek
version: @version@
main: jp.hack.minecraft.hideandseek.Game
api-version: 1.16
depend:
  - Vault
commands:
  hideandseek:
    aliases: hs
    description: hide and seek game command
    usage: "Usage: /<command>"
permissions:
  hideandseek.admin:
      default: op
  hideandseek.player:
    default: true